---
version: "3"

services:
  orion:
    image: fiware/orion:latest
    hostname: orion
    ports:
      - "1026:1026"    
    command: -dbhost mongo-db    
    depends_on:
      - mongo-db

  iotagent:
    image: fiware/iotagent-json:latest
    hostname: iot-agent
    ports:
      - "4041:4041"
      - "7896:7896"
    depends_on:
      - orion
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json

  mongo-db:
    image: mongo:latest
    ports:
      - "8080:80"
